sudo: required

install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential libreadline-dev libffi-dev pkg-config git python python-pip
  - sudo pip install pycodestyle
  - git clone --recurse-submodules https://github.com/micropython/micropython.git
  - cd ./micropython/ports/unix
  - make axtls
  - sudo make install
  - micropython -m upip install micropython-uasyncio micropython-unittest
  - cd ../../../
  - ln -sf `pwd`/tinyweb/ ~/.micropython/lib/tinyweb
  - ls -la

script:
  - pycodestyle --ignore=E501 tinyweb/*.py test/*.py
  - ./test/test_server.py
